# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import message_pb2 as message__pb2


class CalculateSumStub(object):
  """Define the service

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.my_sum = channel.unary_unary(
        '/CalculateSum/my_sum',
        request_serializer=message__pb2.Addends.SerializeToString,
        response_deserializer=message__pb2.Sum.FromString,
        )


class CalculateSumServicer(object):
  """Define the service

  """

  def my_sum(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CalculateSumServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'my_sum': grpc.unary_unary_rpc_method_handler(
          servicer.my_sum,
          request_deserializer=message__pb2.Addends.FromString,
          response_serializer=message__pb2.Sum.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CalculateSum', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
